package tui

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/agustincastanol/glia/internal/store"
)

// tolazyRecords converts a slice of CanonicalRecord to LazyRecord for use in
// filter tests. The raw line bytes are generated by marshaling the record so
// Decode() works correctly in tests that need full fields.
func toLazyRecords(recs []store.CanonicalRecord) []LazyRecord {
	out := make([]LazyRecord, 0, len(recs))
	for _, r := range recs {
		raw, _ := json.Marshal(r)
		out = append(out, LazyRecord{
			CanonicalID: r.CanonicalID,
			Revision:    r.Revision,
			Title:       r.Title,
			Kind:        r.Kind,
			Type:        r.Type,
			rawLine:     raw,
		})
	}
	return out
}

// sampleRecords returns a fixed set of records for filter tests.
func sampleRecords() []store.CanonicalRecord {
	return []store.CanonicalRecord{
		{CanonicalID: "a1", Title: "Fix auth bug", Kind: "observation", Type: "bugfix", Content: "auth token fix", Origin: store.Origin{Provider: "engram"}, SchemaVersion: 1},
		{CanonicalID: "a2", Title: "JWT decision", Kind: "observation", Type: "decision", Content: "use JWT for sessions", Origin: store.Origin{Provider: "engram"}, SchemaVersion: 1},
		{CanonicalID: "a3", Title: "Session end", Kind: "session_summary", Type: "learning", Content: "session wrapped up", Origin: store.Origin{Provider: "claude-mem"}, SchemaVersion: 1},
		{CanonicalID: "a4", Title: "Relation entry", Kind: "relation", Type: "architecture", Content: "depends on auth", Origin: store.Origin{Provider: "engram"}, SchemaVersion: 1},
	}
}

func sampleLazyRecords() []LazyRecord {
	return toLazyRecords(sampleRecords())
}

func TestFilterRecords_Substring_CaseInsensitive(t *testing.T) {
	records := sampleLazyRecords()

	t.Run("matches title", func(t *testing.T) {
		got := filterRecords(records, "auth", "", "")
		if len(got) != 1 {
			t.Errorf("want 1 result for 'auth' in title, got %d", len(got))
		}
	})

	t.Run("matches title jwt", func(t *testing.T) {
		got := filterRecords(records, "jwt", "", "")
		if len(got) != 1 {
			t.Errorf("want 1 result for 'jwt' in title, got %d", len(got))
		}
	})

	t.Run("case insensitive", func(t *testing.T) {
		got := filterRecords(records, "AUTH", "", "")
		if len(got) != 1 {
			t.Errorf("want 1 result for 'AUTH' (case-insensitive in title), got %d", len(got))
		}
	})

	t.Run("no match returns empty slice not nil", func(t *testing.T) {
		got := filterRecords(records, "zzznomatch", "", "")
		if got == nil {
			t.Error("want empty slice, got nil")
		}
		if len(got) != 0 {
			t.Errorf("want 0 results, got %d", len(got))
		}
	})
}

func TestFilterRecords_TypePrefix(t *testing.T) {
	records := sampleLazyRecords()

	got := filterRecords(records, "type:bugfix", "", "")
	if len(got) != 1 {
		t.Fatalf("want 1 result for type:bugfix, got %d", len(got))
	}
	if got[0].CanonicalID != "a1" {
		t.Errorf("want a1, got %s", got[0].CanonicalID)
	}
}

func TestFilterRecords_KindPrefix(t *testing.T) {
	records := sampleLazyRecords()

	got := filterRecords(records, "kind:session_summary", "", "")
	if len(got) != 1 {
		t.Fatalf("want 1 result for kind:session_summary, got %d", len(got))
	}
	if got[0].CanonicalID != "a3" {
		t.Errorf("want a3, got %s", got[0].CanonicalID)
	}
}

func TestFilterRecords_ProviderPrefix(t *testing.T) {
	records := sampleLazyRecords()

	got := filterRecords(records, "provider:claude-mem", "", "")
	if len(got) != 1 {
		t.Fatalf("want 1 result for provider:claude-mem, got %d", len(got))
	}
	if got[0].CanonicalID != "a3" {
		t.Errorf("want a3, got %s", got[0].CanonicalID)
	}
}

func TestFilterRecords_KindFilter(t *testing.T) {
	records := sampleLazyRecords()

	got := filterRecords(records, "", "relation", "")
	if len(got) != 1 {
		t.Fatalf("want 1 relation record, got %d", len(got))
	}
	if got[0].CanonicalID != "a4" {
		t.Errorf("want a4, got %s", got[0].CanonicalID)
	}
}

func TestFilterRecords_TypeFilter(t *testing.T) {
	records := sampleLazyRecords()

	got := filterRecords(records, "", "", "decision")
	if len(got) != 1 {
		t.Fatalf("want 1 decision record, got %d", len(got))
	}
	if got[0].CanonicalID != "a2" {
		t.Errorf("want a2, got %s", got[0].CanonicalID)
	}
}

func TestObsModel_SelectionMove(t *testing.T) {
	dir := t.TempDir()
	m := newObsModel(dir)
	m.SetSize(80, 24)

	m.all = sampleLazyRecords()
	m.applyFilter()

	if m.list.Index() != 0 {
		t.Errorf("want initial index 0, got %d", m.list.Index())
	}

	_, _ = m.Update(tea.KeyMsg{Type: tea.KeyDown})
	if m.list.Index() != 1 {
		t.Errorf("want index 1 after down, got %d", m.list.Index())
	}
}

func TestObsModel_ReloadCmd(t *testing.T) {
	dir := t.TempDir()
	m := newObsModel(dir)
	m.SetSize(80, 24)

	cmd := m.reloadCmd()
	msg := cmd()
	reload, ok := msg.(obsReloadMsg)
	if !ok {
		t.Fatalf("want obsReloadMsg, got %T", msg)
	}
	if reload.err != nil {
		t.Errorf("unexpected error: %v", reload.err)
	}
	// loadRecords on empty dir returns nil — that is valid.
	if len(reload.records) != 0 {
		t.Errorf("want 0 records for empty dir, got %d", len(reload.records))
	}
}

// TestObsModel_ReloadCmd_ReadsFromStoreSubdir is a regression test for the bug
// where the Observations tab showed nothing because reloadCmd read memory.jsonl
// from the project root instead of the .glia store subdirectory. The model
// carries the project root (subprocess --dir calls need it); file reads must
// resolve the .glia subdir themselves.
func TestObsModel_ReloadCmd_ReadsFromStoreSubdir(t *testing.T) {
	root := t.TempDir()
	storeDir := filepath.Join(root, ".glia")
	if err := os.MkdirAll(storeDir, 0o755); err != nil {
		t.Fatal(err)
	}
	rec := makeRecord("zz1", 1, false)
	writeJSONL(t, filepath.Join(storeDir, "memory.jsonl"), []any{rec})

	m := newObsModel(root)
	m.SetSize(80, 24)

	msg := m.reloadCmd()()
	reload, ok := msg.(obsReloadMsg)
	if !ok {
		t.Fatalf("want obsReloadMsg, got %T", msg)
	}
	if reload.err != nil {
		t.Fatalf("unexpected error: %v", reload.err)
	}
	if len(reload.records) != 1 {
		t.Fatalf("want 1 record loaded from .glia subdir, got %d", len(reload.records))
	}
	if reload.records[0].CanonicalID != "zz1" {
		t.Errorf("want zz1, got %s", reload.records[0].CanonicalID)
	}
}

func TestObsModel_FilterFocus(t *testing.T) {
	dir := t.TempDir()
	m := newObsModel(dir)
	m.SetSize(80, 24)
	m.all = sampleLazyRecords()
	m.applyFilter()

	next, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'/'}})
	obs, ok := next.(*obsModel)
	if !ok {
		t.Fatalf("want *obsModel, got %T", next)
	}
	if !obs.filterFocused {
		t.Error("want filter focused after /")
	}

	next2, _ := obs.Update(tea.KeyMsg{Type: tea.KeyEsc})
	obs2, ok := next2.(*obsModel)
	if !ok {
		t.Fatalf("want *obsModel, got %T", next2)
	}
	if obs2.filterFocused {
		t.Error("want filter unfocused after esc")
	}
}

func TestObsModel_FullScreenToggle(t *testing.T) {
	dir := t.TempDir()
	m := newObsModel(dir)
	m.SetSize(80, 24)
	m.all = sampleLazyRecords()
	m.applyFilter()

	next, _ := m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	obs, ok := next.(*obsModel)
	if !ok {
		t.Fatalf("want *obsModel, got %T", next)
	}
	if !obs.fullScreen {
		t.Error("want fullScreen=true after enter")
	}

	next2, _ := obs.Update(tea.KeyMsg{Type: tea.KeyEsc})
	obs2, ok := next2.(*obsModel)
	if !ok {
		t.Fatalf("want *obsModel, got %T", next2)
	}
	if obs2.fullScreen {
		t.Error("want fullScreen=false after esc in full-screen")
	}
}

func TestObsModel_KindCycle(t *testing.T) {
	dir := t.TempDir()
	m := newObsModel(dir)
	m.SetSize(80, 24)
	m.all = sampleLazyRecords()
	m.applyFilter()

	next, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'f'}})
	obs, ok := next.(*obsModel)
	if !ok {
		t.Fatalf("want *obsModel, got %T", next)
	}
	if obs.filterKindIdx != 1 {
		t.Errorf("want filterKindIdx=1 after f, got %d", obs.filterKindIdx)
	}
	// observation kind: should filter to only observations (a1, a2).
	if len(obs.filtered) != 2 {
		t.Errorf("want 2 observations with kind filter, got %d", len(obs.filtered))
	}
}

func TestObsModel_View_ContainsList(t *testing.T) {
	dir := t.TempDir()
	m := newObsModel(dir)
	m.SetSize(80, 24)
	m.all = sampleLazyRecords()
	m.applyFilter()

	view := m.View()
	if view == "" {
		t.Error("View() returned empty string")
	}
}
